#include <c_types.h>

#ifndef _USER_CONFIG_H_
#define _USER_CONFIG_H_

/* for new Espressif SDK compatibility */

#if ((SPI_FLASH_SIZE_MAP == 0) || (SPI_FLASH_SIZE_MAP == 1))
#error "The flash map is not supported"
#elif (SPI_FLASH_SIZE_MAP == 2)
#define SYSTEM_PARTITION_OTA_SIZE					0x6A000
#define SYSTEM_PARTITION_OTA_2_ADDR					0x81000
#define SYSTEM_PARTITION_RF_CAL_ADDR					0xfb000
#define SYSTEM_PARTITION_PHY_DATA_ADDR					0xfc000
#define SYSTEM_PARTITION_SYSTEM_PARAMETER_ADDR				0xfd000
#elif (SPI_FLASH_SIZE_MAP == 3)
#define SYSTEM_PARTITION_OTA_SIZE					0x6A000
#define SYSTEM_PARTITION_OTA_2_ADDR					0x81000
#define SYSTEM_PARTITION_RF_CAL_ADDR					0x1fb000
#define SYSTEM_PARTITION_PHY_DATA_ADDR					0x1fc000
#define SYSTEM_PARTITION_SYSTEM_PARAMETER_ADDR				0x1fd000
#elif (SPI_FLASH_SIZE_MAP == 4)
#define SYSTEM_PARTITION_OTA_SIZE					0x6A000
#define SYSTEM_PARTITION_OTA_2_ADDR					0x81000
#define SYSTEM_PARTITION_RF_CAL_ADDR					0x3fb000
#define SYSTEM_PARTITION_PHY_DATA_ADDR					0x3fc000
#define SYSTEM_PARTITION_SYSTEM_PARAMETER_ADDR				0x3fd000
#elif (SPI_FLASH_SIZE_MAP == 5)
#define SYSTEM_PARTITION_OTA_SIZE					0x6A000
#define SYSTEM_PARTITION_OTA_2_ADDR					0x101000
#define SYSTEM_PARTITION_RF_CAL_ADDR					0x1fb000
#define SYSTEM_PARTITION_PHY_DATA_ADDR					0x1fc000
#define SYSTEM_PARTITION_SYSTEM_PARAMETER_ADDR				0x1fd000
#elif (SPI_FLASH_SIZE_MAP == 6)
#define SYSTEM_PARTITION_OTA_SIZE					0x6A000
#define SYSTEM_PARTITION_OTA_2_ADDR					0x101000
#define SYSTEM_PARTITION_RF_CAL_ADDR					0x3fb000
#define SYSTEM_PARTITION_PHY_DATA_ADDR					0x3fc000
#define SYSTEM_PARTITION_SYSTEM_PARAMETER_ADDR				0x3fd000
#else
#error "The flash map is not supported"
#endif

#endif
